name: C Build and Test

on:
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.h'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: actions/setup-c@v1
      - name: Compile C code
        run: |
          gcc -o my_program main.c utils.c
          ./my_program
      - name: Run Static Code Analysis
        run: cppcheck --enable=all main.c
      - name: Run Tests
        run: ./my_program
